// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://cfuqwvxbwhgfpkvzvnaw.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmdXF3dnhid2hnZnBrdnp2bmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzg5MTYsImV4cCI6MjA3MTgxNDkxNn0.1eoUcnyND7L4l3gmKMLCn4q5t06bVR4En4o7FO1c2Pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});